//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemiMenaxhimitPersonelit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public Personel()
        {
            this.PervojaPunes = new HashSet<PervojaPune>();
        }
    
        public int ID { get; set; }
        public string Emri { get; set; }
        public string Mbiemri { get; set; }
        public string Adresa { get; set; }
        public string Gjinia { get; set; }
        public string Email { get; set; }
        public string Ditelindja { get; set; }
    
        public virtual ICollection<PervojaPune> PervojaPunes { get; set; }
    }
}
