//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemiMenaxhimitPersonelit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemiMenaxhimitPersonelitEntities5 : DbContext
    {
        public SistemiMenaxhimitPersonelitEntities5()
            : base("name=SistemiMenaxhimitPersonelitEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Login> Logins { get; set; }
        public DbSet<Organizata> Organizatas { get; set; }
        public DbSet<Personel> Personels { get; set; }
        public DbSet<PervojaPune> PervojaPunes { get; set; }
    }
}
